/**
 * Build-time fetch of the public repo list.
 *
 * The Projects section used to call GitHub's API from the visitor's browser.
 * That endpoint allows 60 requests/hour per IP for anonymous callers, so
 * anyone behind a shared address -- mobile carriers, offices, CGNAT -- could
 * land on a red "403" error instead of the work. Baking the list in at build
 * time removes that dependency: the page always has real content, and the
 * live call becomes an optional refresh for whoever still has quota.
 *
 * A side benefit: because this data is available during the prerender pass,
 * the repositories end up in the static HTML and are crawlable.
 *
 * Network failure here is not fatal. If GitHub is unreachable or rate-limits
 * the build machine, any previously generated file is kept.
 */
import fs from 'node:fs';
import path from 'node:path';

const USER = process.env.VITE_GITHUB_USERNAME || 'sajeeb-ahmeed';
// The section renders six cards, with a toggle that swaps forks in and out.
// Thirty most-recent repos covers both views with room to spare, without
// shipping the whole account in the bundle.
const LIMIT = 30;
const OUT = path.join(process.cwd(), 'src', 'data', 'repos.generated.ts');
const API = `https://api.github.com/users/${USER}/repos?per_page=100&sort=updated`;

const header = `// AUTO-GENERATED by scripts/fetch-repos.mjs -- do not edit by hand.
// Refreshed on every production build; commit the result so builds work offline.
import type { GithubRepo } from '../types';
`;

function write(repos, generatedAt) {
  const body = `${header}
export const generatedAt = ${JSON.stringify(generatedAt)};

export const generatedRepos: GithubRepo[] = ${JSON.stringify(repos, null, 2)};
`;
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, body);
}

try {
  const res = await fetch(API, { headers: { Accept: 'application/vnd.github+json' } });

  if (!res.ok) throw new Error(`GitHub API responded with ${res.status}`);

  const repos = (await res.json())
    .sort((a, b) => (a.updated_at < b.updated_at ? 1 : -1))
    .slice(0, LIMIT)
    .map((r) => ({
      id: r.id,
      name: r.name,
      htmlUrl: r.html_url,
      description: r.description,
      language: r.language,
      stars: r.stargazers_count,
      forks: r.forks_count,
      topics: r.topics || [],
      updatedAt: r.updated_at,
      homepage: r.homepage || null,
      fork: r.fork,
    }));

  write(repos, new Date().toISOString());
  console.log(`fetch-repos: wrote ${repos.length} repositories to src/data/repos.generated.ts`);
} catch (err) {
  if (fs.existsSync(OUT)) {
    console.warn(`fetch-repos: ${err.message} -- keeping the existing generated file`);
  } else {
    write([], new Date().toISOString());
    console.warn(`fetch-repos: ${err.message} -- wrote an empty list (section will fall back to the live call)`);
  }
}
